Repository natrontech/kubelab, pull requests merged in 2023-11, with the labels that each got.

#37 feat: add events sync
  kubelab-backend/vcluster-values.yaml
Labels: enhancement, size/XS

#39 feat: support check messages in toast
  kubelab-ui/src/routes/labs/[id]/[id]/+layout.svelte
Labels: enhancement, size/L

#40 feat: add confirmation for lab stop
  kubelab-ui/src/lib/components/base/SideOver.svelte
  kubelab-ui/src/lib/components/dashboard/RunningExercises.svelte
  kubelab-ui/src/lib/components/labs/Exercise.svelte
  kubelab-ui/src/routes/app/profile/+page.svelte
  kubelab-ui/src/routes/labs/[id]/[id]/+layout.svelte
Labels: enhancement, size/M

#41 fix: layout exercise done
  kubelab-ui/src/routes/labs/[id]/[id]/+page.svelte
Labels: size/M

#42 feat: add base for code-server
  kubelab-backend/pkg/controller/exercise.go
  kubelab-backend/pkg/env/env.go
  kubelab-backend/pkg/k8s/deployment.go
  kubelab-backend/pkg/k8s/ingress.go
  kubelab-backend/pkg/k8s/service.go
  kubelab-ui/src/lib/components/base/SideOver.svelte
  kubelab-ui/src/lib/stores/data.ts
  kubelab-ui/src/routes/labs/[id]/[id]/+layout.svelte
  kubelab-ui/static/assets/screenshot-dark.png
  kubelab-ui/static/assets/screenshot.png
Labels: enhancement, size/L

#46 feat: update path to ~/exercise/
  kubelab-backend/pkg/k8s/deployment.go
  kubelab-backend/vcluster-values.yaml
  kubelab-ui/src/lib/components/base/SideOver.svelte
  kubelab-ui/src/lib/components/labs/Exercise.svelte
  kubelab-ui/src/lib/components/markdown/CodeComponent.svelte
  kubelab-ui/src/lib/components/markdown/ListComponent.svelte
  kubelab-ui/src/routes/labs/[id]/[id]/+page.svelte
Labels: enhancement, size/M

#55 fix: remove session creation
  kubelab-ui/src/lib/stores/data.ts
Labels: bug, size/M

#56 fix: bug of going to shell
  kubelab-ui/src/lib/components/labs/Lab.svelte
Labels: bug, size/L

#57 chore: update reference link to k8s api
  kubelab-ui/src/routes/material/+page.svelte
Labels: size/XS
